// A real corpus rather than invented strings: the Icelandic names of every
// ISO 3166-1 country, as used by a production country picker. It exercises
// á é í ó ú ý ð þ æ ö in first and interior positions, plus ç.
export const COUNTRY_NAMES: string[] = [
  "Afganistan",
  "Albanía",
  "Alsír",
  "Andorra",
  "Angvilla",
  "Angóla",
  "Antígva og Barbúda",
  "Argentína",
  "Armenía",
  "Arúba",
  "Aserbaísjan",
  "Austur-Kongó",
  "Austur-Tímor",
  "Austurríki",
  "Bahamaeyjar",
  "Bandaríkin",
  "Bandaríska Samóa",
  "Bandarísku Jómfrúaeyjar",
  "Bangladess",
  "Barbados",
  "Barein",
  "Belgía",
  "Belís",
  "Benín",
  "Bermúda",
  "Bosnía og Hersegóvína",
  "Botsvana",
  "Bouveteyja",
  "Brasilía",
  "Bresku Indlandshafseyjar",
  "Bresku Jómfrúaeyjar",
  "Bretland",
  "Brúnei",
  "Bólivía",
  "Búlgaría",
  "Búrkína Fasó",
  "Búrúndí",
  "Bútan",
  "Caymaneyjar",
  "Cooks-eyjar",
  "Curaçao",
  "Danmörk",
  "Djibútí",
  "Dóminíka",
  "Dóminíska lýðveldið",
  "Egyptaland",
  "Eistland",
  "Ekvador",
  "El Salvador",
  "Eritrea",
  "Erlendis",
  "Eþíópía",
  "Falklandseyjar",
  "Filippseyjar",
  "Finnland",
  "Frakkland",
  "Franska Guyana",
  "Franska Pólýnesía",
  "Franska Sankti Martin",
  "Frönsku suðlægu landsvæðin",
  "Færeyjar",
  "Fíjí",
  "Fílabeinsströndin",
  "Gabon",
  "Gambía",
  "Gana",
  "Georgía",
  "Grenada",
  "Grikkland",
  "Grænhöfðaeyjar",
  "Grænland",
  "Guernsey",
  "Gvadelúpeyjar",
  "Gvam",
  "Gvatemala",
  "Gvæjana",
  "Gíbraltar",
  "Gínea",
  "Gínea-Bissá",
  "Haítí",
  "Heard og McDonaldseyjar",
  "Holland",
  "Hollensku Antillaeyjar",
  "Hondúras",
  "Hong Kong",
  "Hvíta-Rússland",
  "Indland",
  "Indónesía",
  "Jamaíka",
  "Japan",
  "Jemen",
  "Jersey",
  "Jólaey",
  "Jórdanía",
  "Kambódía",
  "Kamerún",
  "Kanada",
  "Kasakstan",
  "Katalónía",
  "Katar",
  "Kenía",
  "Kirgistan",
  "Kosta Ríka",
  "Króatía",
  "Kína",
  "Kíribatí",
  "Kókoseyjar",
  "Kólumbía",
  "Kómoreyjar",
  "Kósóvó",
  "Kúba",
  "Kúrdistan",
  "Kúveit",
  "Kýpur",
  "Laos",
  "Lesótó",
  "Lettland",
  "Liechtenstein",
  "Litháen",
  "Líbanon",
  "Líbería",
  "Líbía",
  "Lúxemborg",
  "Madagaskar",
  "Makaó",
  "Makedónía",
  "Malasía",
  "Malaví",
  "Maldíveyjar",
  "Malta",
  "Malí",
  "Marokkó",
  "Marshalleyjar",
  "Martiník",
  "Mayotte",
  "Mexíkó",
  "Minniháttar bandarískar eyjar",
  "Mið-Afríkulýðveldið",
  "Miðbaugs-Gínea",
  "Mjanmar",
  "Moldóva",
  "Mongólía",
  "Montserrat",
  "Máritanía",
  "Máritíus",
  "Míkrónesía",
  "Mónakó",
  "Mósambík",
  "Mön",
  "Namibía",
  "Nepal",
  "Niue",
  "Noregur",
  "Norfolkeyja",
  "Norður-Kórea",
  "Norður-Maríanaeyjar",
  "Nárú",
  "Níger",
  "Nígería",
  "Níkaragva",
  "Nýja-Kaledónía",
  "Nýja-Sjáland",
  "Pakistan",
  "Palestína",
  "Palá",
  "Panama",
  "Papúa Nýja-Gínea",
  "Paragvæ",
  "Perú",
  "Pitcairn",
  "Portúgal",
  "Páfagarður",
  "Pólland",
  "Púertó Ríkó",
  "Rojava",
  "Réunion",
  "Rúanda",
  "Rúmenía",
  "Rússland",
  "Salómonseyjar",
  "Sambía",
  "Sameinuðu arabísku furstadæmin",
  "Samóa",
  "San Marínó",
  "Sankti Barthélemy",
  "Sankti Helena",
  "Sankti Kristófer og Nevis",
  "Sankti Lúsía",
  "Sankti Pierre og Miquelon",
  "Sankti Vinsent og Grenadínur",
  "Saó Tóme og Prinsípe",
  "Senegal",
  "Serbía",
  "Seychelles-eyjar",
  "Simbabve",
  "Singapúr",
  "Slóvakía",
  "Slóvenía",
  "Spánn",
  "Srí Lanka",
  "Suður-Afríka",
  "Suður-Georgía og Suður-Sandvíkureyjar",
  "Suður-Kórea",
  "Suður-Súdan",
  "Suðurskautslandið",
  "Svalbarði og Jan Mayen",
  "Svartfjallaland",
  "Svasíland",
  "Sviss",
  "Svíþjóð",
  "Sádí-Arabía",
  "Síerra Leóne",
  "Síle",
  "Sómalía",
  "Súdan",
  "Súrínam",
  "Sýrland",
  "Tadsjikistan",
  "Tansanía",
  "Tjad",
  "Tonga",
  "Trínidad og Tóbagó",
  "Turks- og Caicoseyjar",
  "Tyrkland",
  "Tæland",
  "Tævan",
  "Tékkland",
  "Tógó",
  "Tókelá",
  "Túnis",
  "Túrkmenistan",
  "Túvalú",
  "Ungverjaland",
  "Vanúatú",
  "Venesúela",
  "Vestur-Kongó",
  "Vestur-Sahara",
  "Víetnam",
  "Wallis- og Fútúnaeyjar",
  "Álandseyjar",
  "Ástralía",
  "Írak",
  "Íran",
  "Írland",
  "Ísland",
  "Ísrael",
  "Ítalía",
  "Óman",
  "Úganda",
  "Úkraína",
  "Úrúgvæ",
  "Úsbekistan",
  "Þýskaland",
];
